name: Node.js CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Node.js ${{matrix.node-version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: Install the package and run tests
      run: |
        npm ci
        npm run build --if-present
        npm test
